#!/usr/bin/python3
# File:		gpsi2c
# Version:	20240128
# Author: 	Sifan
# Description:	reads Adafruit's i2c GPS (PMTK220)

import time, board, sys
import adafruit_gps
from datetime import datetime, timezone
from dateutil import tz
import ephem

ltime = datetime.now().strftime("%Y%m%d %H:%M:%S")
utime = datetime.utcnow().strftime("%Y%m%d %H:%M:%S")

i2c = board.I2C()  # uses board.SCL and board.SDA

def gpsloop():
    gpsfix = 0
    altitude = 0
    geoid = 0
    fixtimeU= ""
    gltime = gutime = "00000000 00:00:00"

    try:
        gps = adafruit_gps.GPS_GtopI2C(i2c, debug=False)  # Use I2C interface
        gps.send_command(b"PMTK314,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0")
        gps.send_command(b"PMTK220,1500")
    except:
        print("Issue with I2C GPS")
        return(0, 0, gltime, gutime, 999.999999, 999.9999999, 0, 0)

    loopcntr = 3
    while loopcntr:
        gps.update()
        loopcntr -= 1
        if not gps.has_fix:
            continue
        if gps.timestamp_utc.tm_year == 0:
            continue

        gps.update()
        ztz = datetime(*gps.timestamp_utc[:6])
        print(ztz)
        gutime = f"{ztz:%Y%m%d %H:%M:%S}"
        ltz = datetime(*gps.timestamp_utc[:6]).replace(tzinfo=timezone.utc).astimezone(tz=None)
        gltime = f"{ltz:%Y%m%d %H:%M:%S %Z}"

        gpsfix = gps.fix_quality
        if gpsfix >= 3:
            gpsfix = 3

        if gps.altitude_m is not None:
            altitude = gps.altitude_m

        if gps.height_geoid is not None:
            geoid = gps.height_geoid

        return(gpsfix, ztz, gltime, gutime, gps.latitude, gps.longitude, altitude, geoid)

    print("Issue with I2C GPS")
    return(0, 0, gltime, gutime, 999.999999, 999.9999999, 0, 0)


### Main
(gpsfix, ztz, gltime, gutime, latitude, longitude, altitude, geoid) = gpsloop()

# calculate local sidereal time
if gpsfix >=1:
    obs = ephem.Observer()
    obs.lon = longitude
    obs.lat = latitude
    obs.epoch = '2020'
    obs.date = ephem.Date(ztz)

print("--- Local -----------------")
print(f"System Time: {utime} UTC")
print(f"System Time: {ltime} LOC")
print("--- GPS -------------------")
print('Fix:         %s' % (("NO FIX", "2D", "3D")[gpsfix]))
print(f"GPS Time:    {gutime} UTC")
print(f"GPS Time:    {gltime}")
if gpsfix >= 1:
    print(f"LST:         {obs.sidereal_time()}")
print(f"Latitude:    {latitude:.7f} deg")
print(f"Longitude:   {longitude:.7f} deg")
if gpsfix == 2:
    print(f"Altitude:   {altitude:.1f} m")
    #print(f"Geiod H:   {geoid:.2f} m")

sys.exit(0)


